### ISSUE TITLE
Pairing Logic

### ISSUE THREAD

**Issue by twistedpixel** [timelery/NewestSamsung-RemoteControl#4]
@timelery Hey, I know it was a while ago but do you still have the pairing logic info you offered to email? I'd really appreciate it!

Sorry for abusing your GitHub issues for this but I didn't know how else to contact you.

throwaway836@twistsouth.com

Thanks

**Comment by timelery** [comment]
The low level pairing logic is in c++ from Samsung and wrapped in a DLL. I do not have visibility to the source as decompiling it is not possible.

I can be reached directly at telery@codimation.com

**Comment by twistedpixel** [comment]
Ah well, thanks for getting back to me anyway. I may try contacting one of the developers of iOS remotes that work with the 2015 TVs and see if they'll throw us a bone.

**Comment by eclair4151** [comment]
Any chance you can point me to where you downloaded the sdk from? i cant seem to tell where you got these drivers from

**Comment by eclair4151** [comment]
@timelery any chance you can send a link to where you got the sdk with the dlls in it?
